version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "htmlresume"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-atay7ha84pyn"
s3_prefix = "htmlresume"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

